[metadata]
creation_date = "2024-02-14"

[rule]
name = "Suspicious PowerShell Execution"
author = ['Security Team']
risk_score = 65
severity = "high"

[[rule.threat]]
framework = "MITRE ATT&CK"
tactic = { name = "Execution", id = "TA0002" }

[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
[[rule.threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
