[metadata]
creation_date = "2024-02-14"

[rule]
name = "Ransomware File Extensions"
author = "Threat Intel"
risk_score = 85
severity = "critical"

[[rule.threat]]
framework = "MITRE ATT&CK"
tactic = { name = "Impact", id = "TA0040" }

[[rule.threat.technique]]
id = "T1486"
name = "Data Encrypted for Impact"
