name: Updating Detections

on:
  push:
    branches:
      - main
    paths:
      - '**.toml'
      - 'detections\**'
  workflow_dispatch:

jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14.3'

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v47

      - name: Run Update Script
        env:
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${CHANGED_FILES}; do
            echo "$file was changed"
          done  
      - run: pip install requests
      - run: python development/update_alert.py
