name: Metrics

on:
  workflow_dispatch:


jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPORT_METRICS_KEY }}
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.14.3'
      - run: pip install python-dateutil 
      - run: python development/toml_to_report.py
      - run: python metrics/toml_to_csv.py
      - run: python metrics/toml_to_navigator.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updating Metrics"
          git push -f
      
